"use client";
import {useMemo,useState} from "react";
const topics=["感情","事业","生意","财运","求职","考试","出行","失物"];
const methods=[{id:"time",name:"时间起卦",note:"以此刻时间起卦",mark:"时"},{id:"two",name:"两数起卦",note:"凭直觉输入两个数字",mark:"二"},{id:"three",name:"三数起卦",note:"第三个数字确定动爻",mark:"三"},{id:"random",name:"随机起卦",note:"静心后交给当下",mark:"易"}];
const trigrams=[{name:"坤",symbol:"☷",nature:"地"},{name:"震",symbol:"☳",nature:"雷"},{name:"坎",symbol:"☵",nature:"水"},{name:"兑",symbol:"☱",nature:"泽"},{name:"艮",symbol:"☶",nature:"山"},{name:"离",symbol:"☲",nature:"火"},{name:"巽",symbol:"☴",nature:"风"},{name:"乾",symbol:"☰",nature:"天"}];
const mod=(v:number,b:number)=>v%b||b;
export default function Home(){
 const [question,setQuestion]=useState("");const [topic,setTopic]=useState("事业");const [method,setMethod]=useState("time");const [numbers,setNumbers]=useState([18,27,9]);const [result,setResult]=useState<null|{upper:number;lower:number;moving:number}>(null);
 const reading=useMemo(()=>result?{upper:trigrams[result.upper-1],lower:trigrams[result.lower-1],moving:result.moving}:null,[result]);
 function cast(){const now=new Date();let [a,b,c]=numbers;if(method==="time"){a=now.getFullYear()+now.getMonth()+1+now.getDate();b=a+now.getHours();c=b+now.getMinutes()}if(method==="random"){a=Math.ceil(Math.random()*99);b=Math.ceil(Math.random()*99);c=Math.ceil(Math.random()*99)}setResult({upper:mod(a,8),lower:mod(b,8),moving:mod(method==="two"?a+b:c,6)});setTimeout(()=>document.getElementById("result")?.scrollIntoView({behavior:"smooth"}),80)}
 return <main>
  <header className="nav"><a className="brand" href="#top"><span className="seal">梅</span><span>梅花问易<small>AI · MEIHUA</small></span></a><nav><a href="#how">如何起卦</a><a href="#pricing">价格</a><button className="ghost">我的卦例</button></nav></header>
  <section className="hero" id="top"><div className="orbit one"/><div className="orbit two"/><p className="eyebrow">古法为骨 · AI 为用 · 现实为归</p><h1>问一事，见其势<br/><em>在变化中找到方向</em></h1><p className="lead">遵循梅花易数确定性规则起卦，以现代白话梳理趋势、关键变量与下一步行动。30 秒，得到一份能读懂的启发。</p><div className="trust"><span>✓ 过程透明</span><span>✓ 隐私保护</span><span>✓ 每日免费 1 次</span></div></section>
  <section className="consult-card"><Step n="01" title="你想问什么？" desc="一次只问一件具体的事，答案会更清晰。"/><textarea value={question} onChange={e=>setQuestion(e.target.value)} maxLength={120} placeholder="例如：未来三个月，我是否适合启动新的轮胎品牌项目？"/><div className="row-label"><span>选择问题领域</span><small>{question.length}/120</small></div><div className="chips">{topics.map(t=><button key={t} onClick={()=>setTopic(t)} className={topic===t?"active":""}>{t}</button>)}</div><div className="divider"/><Step n="02" title="选择起卦方式" desc="规则只负责排卦，AI 不会改变卦象。"/><div className="method-grid">{methods.map(m=><button key={m.id} onClick={()=>setMethod(m.id)} className={method===m.id?"method active":"method"}><b>{m.mark}</b><span><strong>{m.name}</strong><small>{m.note}</small></span></button>)}</div>{(method==="two"||method==="three")&&<div className="number-box">{numbers.slice(0,method==="two"?2:3).map((n,i)=><label key={i}>第{i+1}个数<input type="number" value={n} onChange={e=>{const x=[...numbers];x[i]=Number(e.target.value);setNumbers(x)}}/></label>)}</div>}<button className="primary" onClick={cast} disabled={!question.trim()}><span>开始起卦</span><small>{question.trim()?"静心一念，观此刻之变":"请先写下你的问题"}</small></button><p className="notice">本工具用于文化研究与个人反思，不替代医疗、法律或投资等专业意见。</p></section>
  {reading&&<section className="reading" id="result"><p className="eyebrow">你的本次卦象</p><h2>{reading.upper.nature}{reading.lower.nature}之象</h2><div className="hexagram"><div><span>{reading.upper.symbol}</span><small>上卦 · {reading.upper.name}</small></div><i>第 {reading.moving} 爻动</i><div><span>{reading.lower.symbol}</span><small>下卦 · {reading.lower.name}</small></div></div><div className="insight"><span>核心结论</span><h3>当下宜先观察结构，再决定推进速度。</h3><p>这件事并非没有机会，但关键不在“是否立刻行动”，而在于你能否先理清资源、合作关系和承受范围。先做小规模验证，比一次投入更符合当前之势。</p></div><div className="actions"><Info label="趋势" title="先缓后明" text="短期信息仍在汇集，中段会出现更明确的判断依据。"/><Info label="关键变量" title="合作与边界" text="把责任、成本和退出条件说清楚，局势会更顺。"/><Info label="行动建议" title="七天内验证" text="先完成一个最小测试，并用真实反馈决定下一步。"/></div><button className="deep">解锁完整报告 · $4.99<small>查看体用、互卦、变卦与三阶段推演</small></button></section>}
  <section className="how" id="how"><p className="eyebrow">不是神秘答案，而是一套思考路径</p><h2>一次问易，五步看清问题</h2><div className="steps">{[["1","问","写下一个具体问题"],["2","起","按固定规则生成卦象"],["3","析","AI 将古义翻译成白话"],["4","行","得到现实行动建议"],["5","复","保存卦例，日后回看"]].map(x=><article key={x[0]}><b>{x[0]}</b><strong>{x[1]}</strong><p>{x[2]}</p></article>)}</div></section>
  <section className="pricing" id="pricing"><div><p className="eyebrow">清晰定价 · 随需选择</p><h2>先免费了解，再决定是否深入</h2></div><div className="price-list"><Price name="免费摘要" price="$0" note="每日 1 次"/><Price name="完整报告" price="$4.99" note="单次解锁" featured/><Price name="深度报告" price="$12.99" note="三阶段推演"/><Price name="月度会员" price="$14.99" note="连续使用"/></div></section>
  <footer><div className="brand"><span className="seal">梅</span><span>梅花问易<small>观变 · 知机 · 笃行</small></span></div><p>文化研究与个人反思工具 · 请理性看待结果</p><span>© 2026 梅花问易</span></footer>
 </main>}
function Step({n,title,desc}:{n:string;title:string;desc:string}){return <div className="step-title"><span>{n}</span><div><h2>{title}</h2><p>{desc}</p></div></div>}
function Info({label,title,text}:{label:string;title:string;text:string}){return <article><small>{label}</small><strong>{title}</strong><p>{text}</p></article>}
function Price({name,price,note,featured=false}:{name:string;price:string;note:string;featured?:boolean}){return <article className={featured?"featured":""}><span>{name}</span><strong>{price}</strong><small>{note}</small></article>}
